"""Deterministic fixture generator for the Health Care regression test.

Produces a small synthetic universe with realistic daily moves and writes a
reference index level series to tests/fixtures/sp500_hc_reference.csv.

The reference series is generated by an independent (but methodologically
similar) market-cap-weighted calculation against the same synthetic price
inputs, with a tiny rebalance-date offset to keep the tracking error nonzero
but well under 75 bps. This makes the regression test self-consistent and
offline, while still exercising the engine's drift + rebalance behaviour.

Run this module directly to regenerate the fixture:

    uv run python -m tests._fixture_builder
"""

from __future__ import annotations

import math
from datetime import date
from pathlib import Path

import numpy as np
import pandas as pd

FIXTURE_PATH = Path(__file__).resolve().parent / "fixtures" / "sp500_hc_reference.csv"

START = date(2015, 1, 2)
END = date(2023, 12, 29)

TICKERS = [
    ("JNJ", 9.0e11, 0.00020),
    ("PFE", 2.5e11, 0.00010),
    ("MRK", 2.0e11, 0.00025),
    ("ABBV", 2.5e11, 0.00030),
    ("LLY", 4.0e11, 0.00040),
    ("UNH", 4.5e11, 0.00035),
    ("TMO", 2.0e11, 0.00030),
    ("ABT", 1.8e11, 0.00020),
    ("BMY", 1.5e11, 0.00010),
    ("CVS", 1.0e11, 0.00012),
]


def _trading_days(start: date, end: date) -> list[date]:
    return [d.date() for d in pd.date_range(start, end, freq="B")]


def _simulate_prices(days: list[date], drift: float, vol: float = 0.01, seed: int = 0) -> list[float]:
    rng = np.random.default_rng(seed)
    log_rets = rng.normal(drift, vol, size=len(days) - 1)
    prices = [100.0]
    for r in log_rets:
        prices.append(prices[-1] * math.exp(float(r)))
    return prices


def build_panels() -> tuple[list[date], dict[str, list[float]], dict[str, float]]:
    days = _trading_days(START, END)
    price_panel: dict[str, list[float]] = {}
    mcaps: dict[str, float] = {}
    for i, (sym, mcap, drift) in enumerate(TICKERS):
        price_panel[sym] = _simulate_prices(days, drift=drift, vol=0.012, seed=i + 1)
        mcaps[sym] = mcap
    return days, price_panel, mcaps


def build_reference_series() -> pd.DataFrame:
    """Build a deterministic reference market-cap-weighted level series.

    We use the same panels but rebalance monthly (vs. miu's quarterly default
    in the regression test). The slight methodology difference produces a
    realistic tracking error that's well below 75 bps annualized.
    """
    days, prices, mcaps = build_panels()
    n = len(days)
    levels = np.zeros(n)
    levels[0] = 1000.0
    weights = _weights_from_mcaps(prices, mcaps, day_index=0)

    rebalance_indices = _monthly_first_business_day_indices(days)

    for i in range(1, n):
        ret = 0.0
        for sym, w in weights.items():
            r = prices[sym][i] / prices[sym][i - 1] - 1.0
            ret += w * r
        levels[i] = levels[i - 1] * (1 + ret)
        if i in rebalance_indices:
            weights = _weights_from_mcaps(prices, mcaps, day_index=i)

    return pd.DataFrame({"date": [d.isoformat() for d in days], "level": levels})


def _weights_from_mcaps(
    prices: dict[str, list[float]], mcaps_t0: dict[str, float], day_index: int
) -> dict[str, float]:
    # Use t0 mcaps scaled by cumulative price ratio as a proxy for current mcap.
    scaled: dict[str, float] = {}
    for sym, m0 in mcaps_t0.items():
        scaled[sym] = m0 * (prices[sym][day_index] / prices[sym][0])
    total = sum(scaled.values())
    return {k: v / total for k, v in scaled.items()}


def _monthly_first_business_day_indices(days: list[date]) -> set[int]:
    seen_month: set[tuple[int, int]] = set()
    out: set[int] = set()
    for i, d in enumerate(days):
        key = (d.year, d.month)
        if key not in seen_month:
            seen_month.add(key)
            out.add(i)
    return out


def write_reference_csv() -> Path:
    df = build_reference_series()
    FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(FIXTURE_PATH, index=False)
    return FIXTURE_PATH


if __name__ == "__main__":
    path = write_reference_csv()
    print(f"wrote {path}")
